gara/urls.py
from django.urls import path, include
from django.conf.urls import include, url
from . import views
from django.contrib.auth import views as auth_views
from django.contrib import admin

app_name='gara'

urlpatterns = [
    path('', views.customer_login_view, name='login'),
    path('admin', admin.site.urls),
    path('add-request', views.tiep_nhan,name='add-request'),
    path('view-request',views.view_request,name='view-request'),
    url(r'^login/$', views.customer_login_view, name='login'),
    url( r'^logout/$',auth_views.LogoutView.as_view(template_name="profile/logout.html"), name="logout"),
    path('create_new_staff', views.createStaffAccount , name = 'create-staff-account'),
    path('',include('django.contrib.auth.urls')),
    path('profile/<username>', views.profile, name = 'profile'),
    path('dashboard/<username>', views.customer_dashboard_view, name = 'dashboard'),
    path('edit-profile/<username>', views.edit_customer_profile_view, name='edit-profile'),
    path('edit-account/<username>', views.edit_customer_account_view, name='edit-account'),
    path('<username>/nhap_biensothutien',views.nhapbienso_phieuthu,name='view-request'),
    path('<username>/nhap_phieuthu/<int:maxe>',views.xacnhan_phieuthu,name='view-view'),
    path('<username>/view_phieuthu/<int:maphieuthutien>',views.view_phieuthu,name='view-view'),
    path('<username>/nhap_biensosua',views.nhapbiensosua,name='nhapbiensosua'),
    path('<username>/view_phieusua/<int:maphieusuachua>',views.view_phieusua,name='view-phieusua'),
    path('<username>/view_ctphieusua/<int:mact_phieusuachua>',views.view_ctphieusuachua,name='view_ctphieusuachua'),
    path('<username>/delete_ctphieusua/<int:mact_phieusuachua>',views.delete_ctphieusua,name='delete_ctphieusua'),
    path('<username>/delete_chitietvattu/<int:mact_vattuphutung>/<int:mact_phieusuachua>/<int:maphieusuachua>',views.delete_chitietvattu,name='delete_chitietvattu'),
    path('<username>/add_request', views.tiep_nhan,name='add-request'),
    path('<username>/update_request/<pk>',views.update_request,name='update_request'),    
    path('<username>/request',views.view_request,name='view-request'),
    path('<username>/view_baocaoton', views.view_baocaoton),
    path('<username>/baocaoton', views.baocaoton_luachon),
    path('<username>/save_baocaoton',views.save_baocaoton),
    path('<username>/baocaodoanhso', views.Bao_Cao_Doanh_So),
    path('<username>/post_bsds',views.search_bcds, name="post_bsds"),
    path('<username>/thamso', views.regular_update, name="index"),
    path('save',views.save_regular_update, name="save"),
    path('<username>/update_quydinh/<mts>', views.update_quydinh, name='update_quydinh'),
    path('<username>/nhap_vtpt', views.nhap_vtpt, name='nhap_vtpt'),
    path('<username>/nhap_hieuxe', views.them_hieuxe, name="nhap-hieu-xe"),
    path('<username>/nhap_tiencong', views.them_tiencong, name="them-hieu-xe"),
    path('<username>/delete_quydinh/<mts>', views.delete_quydinh),
    path('<username>/get_bd',views.get_bd),
    path('<username>/after_search', views.after_search, name = "after_search"),
]

gara_management/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('gara.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

gara/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import *
import datetime
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.forms import AuthenticationForm

# class TiepNhanForm(forms.ModelForm):
#     class Meta:
#         model= PhieuTiepNhan
#         fields=['tenchuxe','bienso','hieuxe','dienthoai','diachi']

# class CustomerUserForm(forms.ModelForm):
#     class Meta:
#         model=User
#         fields=['first_name','last_name','username','password']
#         widgets = {
#         'password': forms.PasswordInput()
#         }
#         fields= '__all__'

# class CustomerForm(forms.ModelForm):
#     class Meta:
#         model=models.Staff
#         fields=['address','mobile','profile_pic']
#         fields= '__all__'

#Phan cua Chau Tan -20520926
class RegisterForm(forms.ModelForm):
    firstname = forms.CharField(max_length=20)
    lastname = forms.CharField(max_length=20)
    mobile = forms.CharField(max_length=10)
    username = forms.CharField(max_length=20)
    address = forms.CharField(max_length=100)
    password = forms.CharField(max_length=12)
    emails = forms.EmailField(max_length=90)
    profile_pic = forms.ImageField()
    class Meta:
        model= Staff
        fields=['username','firstname','lastname','emails','password','mobile', 'address','profile_pic']
        widgets = {
            'password': forms.PasswordInput()
        }
class StaffUpdateForm(UserChangeForm):
    emails = forms.CharField(max_length=90)
    class Meta:
        model = Staff
        fields= ['profile_pic','firstname','lastname','emails','mobile','address']
        # fields = '__all__'
        widgets = {
            'password': forms.PasswordInput()
        }
class StaffUpdateAccount(UserChangeForm):
    password = forms.CharField(max_length=20)
    class Meta:
        model = Staff
        fields = ['username','password']
        widgets = {
            'password': forms.PasswordInput()
        }
# Phan cua Ngo Duc Vu -20520950
class NhapBienSoThu(forms.Form):
    bienso=forms.ModelChoiceField(queryset=Xe.objects.filter(tienno__gt=0))
class NhapSoTienThu(forms.Form):
    sotienthu=forms.IntegerField()
class NhapBienSoSua(forms.Form):
    bienso=forms.ModelChoiceField(queryset=Xe.objects.all().values_list('bienso',flat=True))
class NhapCTSuaChua(forms.Form):
    # maphieusuachua=forms.ModelChoiceField(queryset=PhieuSuaChua.objects.all())
    solan=forms.IntegerField()
    loaitiencong=forms.ModelChoiceField(queryset=TienCong.objects.all())
    # tiencong=forms.IntegerField()
    noidung=forms.CharField(max_length=100)
    # tongtien=forms.IntegerField()
class NhapCT_VatTuPhuTung(forms.Form):
    tenvattuphutung=forms.ModelChoiceField(queryset=VatTuPhuTung.objects.all())   #.values_list('tenvattuphutung',flat=True))
    soluong=forms.IntegerField()

# Phan cua Cao Van Hung


class TiepNhanForm(forms.ModelForm):
    class Meta:
        model=PhieuTiepNhan
        fields=['tenchuxe','bienso','hieuxe','dienthoai','diachi']

class AskDateForm(forms.Form):
    date=forms.DateField(widget=forms.SelectDateWidget())

# Phan cua Nguyen Tri

class CapNhatQuyDinh(forms.ModelForm):
    class Meta:
        # def __init__(self):
        #     print("in init")
        model = QuyDinhHienHanh
        fields = ['MaThamSo','TenThamSo','GiaTri']
        widgets = {
            'GiaTri': forms.TextInput(attrs={'class':'form_GiaTri'}),
            'TenThamSo': forms.TextInput(attrs={'class':'form_TenThamSo'})
        }

class NhapCTVatTuPhuTung(forms.ModelForm):
    class Meta:
        model = VatTuPhuTung
        fields = ['tenvattuphutung','soluong','dongia']
     
class ThemHieuXe(forms.Form):
        tenhieuxe = forms.CharField(max_length=50)
class ThemTienCong(forms.Form):
    loaitiencong = forms.CharField(max_length=100)
    tiencong = forms.IntegerField(min_value=0)

gara/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import *
from datetime import date
from .forms import *
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.models import User, Group
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import AuthenticationForm
from django.contrib import messages
from django.http import HttpResponseRedirect, HttpResponse
from imp import C_BUILTIN
from django.db.models import Sum, Count
import pandas as pd

def logout(request):
    return render(request,'gara/logout.html',{})

def home(request):
    return render(request, 'gara/home.html',{})

def is_staff(user):
    return user.groups.filter(name='STAFF').exists()

def is_admin(user):
    return user.groups.filter(name='ADMIN').exists()

@user_passes_test(is_admin)
@login_required(login_url='/login')
def createStaffAccount(request):
    form = RegisterForm()
    if request.method == "POST":
        form = RegisterForm(request.POST, request.FILES)
        print(form.errors)
        if form.is_valid():
            print(form.cleaned_data)
            print('valid')
            username = request.POST['username']
            password = request.POST['password']
            lastname = request.POST['lastname']
            firstname = request.POST['firstname']
            mobile = request.POST['mobile']
            emails = request.POST['emails']
            profile_pic = request.FILES['profile_pic']
            address = request.POST['address']
            Staff.objects.create(username=username, password=password, lastname=lastname,
                                    firstname=firstname, mobile=mobile, emails=emails, 
                                    address=address , profile_pic=profile_pic)
            user = User.objects.create_user(username=username, password=password, 
                                first_name=firstname, last_name=lastname, email=emails)
            user.is_staff = True
            user.save()
            my_customer_group = Group.objects.get_or_create(name='STAFF')
            my_customer_group[0].user_set.add(user)
            messages.success(request, f'Add staff {username} successfully! !!')
        else:
            messages.warning(request,'Invalid form, please filling a again!')
    context = {'userForm': form, 'username':request.user.username}
    return render(request, 'profile/create_new_staff.html', context)

def customer_login_view(request):
    form = AuthenticationForm()
    if request.method== 'POST':
        username = request.POST['username']
        password = request.POST['password']
        request.session['rawpassword'] = password
        print(f'username {username} password {password}')
        print(form.is_valid())
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            print('Log In sucessfully')
            return redirect(f'../profile/{username}')
        else:
            messages.warning(request, 'Đăng nhập thất bại! Kiểm tra thông tin của bạn và đăng nhập lại')
    context = {'form': form}
    
    return render(request, 'profile/customerlogin.html', context)

@login_required(login_url='/login')
def profile(request, username):
    try:
        cus = Staff.objects.get(username=username)
        profile_pic = '../' + cus.profile_pic.url
        print(profile_pic)
    except:
        rawpassword = request.session.get('rawpassword')
        password = request.user.password
        cus = Staff.objects.create(username=username, password=rawpassword)
        cus.is_admin = True
        profile_pic = "../static/profile_pic/CustomerProfilePic/images.jpg"
        cus.profile_pic = profile_pic
        user = User.objects.get(username=username, password=password)
        user.save()
        my_customer_group = Group.objects.get_or_create(name='ADMIN')
        my_customer_group[0].user_set.add(user)
        cus.save()

    context = {'customer': cus, 'username': username, 'picture': profile_pic}
    return render(request,'profile/Profile.html', context)



@login_required(login_url='/login')
def customer_dashboard_view(request, username):
    cus = Staff.objects.get(username=username)
    profile_pic = '../' + cus.profile_pic.url
    context = {'customer': cus, 'username': username, 'picture': profile_pic}
    return render(request, 'profile/customer_dashboard.html', context)

@login_required(login_url='/login')
def edit_customer_profile_view(request, username):
    staff = get_object_or_404(Staff, username=username)
    staffUpdate_form = StaffUpdateForm(instance= staff)
    picture = '../' + staff.profile_pic.url
    print(staff)
    if request.method=='POST':
        staffUpdate_form = StaffUpdateForm(request.POST, request.FILES, instance=staff)
        if staffUpdate_form.is_valid():
            print('valid')
            staff = staffUpdate_form.save()
            staff.save()
            return HttpResponseRedirect(f'../profile/{username}')
    mydict={'customerForm':staffUpdate_form, 'picture': picture}
    return render(request,'profile/edit_customer_profile.html',mydict)

@login_required(login_url='/login')
def edit_customer_account_view(request, username):
    staff = get_object_or_404(Staff, username=username)
    user = User.objects.get(username=request.user.username)
    StaffUpdate_Account = StaffUpdateAccount(instance=staff)
    picture = '../' + staff.profile_pic.url
    if request.method=='POST':
        StaffUpdate_Account = StaffUpdateAccount(request.POST ,instance=staff)
        print(StaffUpdate_Account.errors)
        if StaffUpdate_Account.is_valid():
            print('valid')
            user.username = request.POST['username']
            user.set_password(request.POST['password'])
            user.save()
            staff = StaffUpdate_Account.save()
            staff.password = request.POST['password']
            staff.save()
            return redirect('../login')
    mydict = {'userForm':StaffUpdate_Account, 'picture':picture}
    return render(request,'profile/edit_customer_account.html', mydict)

#------------------------------------------------------------------------------
@login_required(login_url='/login')
def nhapbienso_phieuthu(request, username):
    enquiry= NhapBienSoThu()
    staff = Staff.objects.get(username=username)
    picture = '../' + staff.profile_pic.url
    if request.method=='POST':
        enquiry= NhapBienSoThu(request.POST)
        if enquiry.is_valid():
            print('enquiry is valid')
            print(request.POST['bienso'])
            xe_x=Xe.objects.get(maxe=request.POST['bienso']) 
            return redirect(f'../{username}/nhap_phieuthu/{xe_x.maxe}')
    context= {'enquiry':enquiry, 'customer': staff, 'picture': picture}        
    return render(request,'phieuthutien/nhapbienso_phieuthu.html',context)

@login_required(login_url='/login')
def xacnhan_phieuthu(request,maxe, username):
    nhapsotienthu=NhapSoTienThu()
    staff = Staff.objects.get(username=username)
    picture = '../' + staff.profile_pic.url
    xe_x=Xe.objects.get(maxe=maxe)
    khach_x=KhachHang.objects.get(makhachhang=xe_x.makhachhang_id) 
    list_phieusua=PhieuSuaChua.objects.all().filter(maxe_id=xe_x.maxe)
    xe_x.save()
    context= {'nhapsotienthu':nhapsotienthu,'xe_x': xe_x,'khach_x':khach_x, 
                "customer": staff, "picture":picture, "data":list_phieusua} 
    if request.method=='POST':
        nhapsotienthu=NhapSoTienThu(request.POST)  
        if nhapsotienthu.is_valid():
            print('enquiry is valid')
            tienthu=nhapsotienthu.cleaned_data['sotienthu']
            if tienthu>xe_x.tienno:
                messages.warning(request, 'Số tiền nhập không hợp lệ')
                return render(request,'phieuthutien/nhapsotienthu.html',context)  
            elif tienthu<=xe_x.tienno: 
                phieuthutien_x=PhieuThuTien.objects.create(maxe_id=xe_x.maxe,sotienthu=tienthu)
                xe_x.tienno-= tienthu
                xe_x.save()
                print('da luu vao database')
                messages.success(request, 'Thanh toán thành công!')

    return render(request,'phieuthutien/nhapsotienthu.html',context)       

@login_required(login_url="/login")
def view_phieuthu(request,maphieuthutien):
    phieuthu=PhieuThuTien.objects.get(maphieuthutien=maphieuthutien)
    xe_x=Xe.objects.get(maxe=phieuthu.maxe)
    context={'xe_x':xe_x,'phieuthu':phieuthu}
    return render(request,'phieuthutien/view_phieuthu.html',context)       

@login_required(login_url="/login")
def nhapbiensosua(request,username):
    enquiry= NhapBienSoSua()
    staff = Staff.objects.get(username=username)
    picture = '../' + staff.profile_pic.url
    if request.method=='POST':
        enquiry=NhapBienSoSua(request.POST)
        print(request.POST['bienso'])
        xe_x=Xe.objects.get(bienso=request.POST['bienso'])
        phieusua_x=PhieuSuaChua.objects.create(maxe_id=xe_x.maxe,tongthanhtien=0)
        phieusua_x.save()
        return redirect(f'../{username}/view_phieusua/{phieusua_x.maphieusuachua}')
    return render(request,'phieusuachua/nhapbiensosua.html', {'enquiry':enquiry, 'customer': staff, 'picture':picture}, ) 

@login_required(login_url="/login")
def view_phieusua(request ,maphieusuachua, username):
    phieusua=PhieuSuaChua.objects.get(maphieusuachua=maphieusuachua)
    xe_x=Xe.objects.get(maxe=phieusua.maxe_id)
    data=CT_PhieuSuaChua.objects.all().filter(maphieusuachua=maphieusuachua)
    staff = Staff.objects.get(username=username)
    picture = '../' + staff.profile_pic.url
    enquiry=NhapCTSuaChua()
    context= {'phieusua':phieusua,'xe_x':xe_x,'data':data,'enquiry':enquiry, "customer":staff, "picture":picture}
    if request.method=='POST':
        print('request method la POST')
        enquiry=NhapCTSuaChua(request.POST)
        if enquiry.is_valid():
            print('enquiry is valid')

templates/gara/add_request.html
{% extends 'gara/customerbase.html' %}
{% load widget_tweaks %}
{% block content %}
<head>
  <style media="screen">
    input[type=text], select,input[type=number] , textarea{
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    border-radius: 4px;
    box-sizing: border-box;
  }

  input[type=submit] {
    width: 100%;
    background-color: #4CAF50;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    border-radius: 4px;
    cursor: pointer;
  }

  input[type=submit]:hover {
    background-color: #45a049;
  }


  </style>


</head>



<br><br><br><br><br>
<h1 style="text-align:center;">TẠO PHIẾU TIẾP NHẬN</h1>
<div>
  <form method="post" style="margin-left:200px;margin-right:200px;">
      {% csrf_token %}
    <label for="category">Tên chủ xe</label>
    {% render_field enquiry.tenchuxe class="form-control"  %}<br>

    <label for="vehicle_no">Biển số</label>
    {% render_field enquiry.bienso class="form-control" placeholder="Biển số" %}

    <label for="vehicle_name">Hiệu xe</label>
    {% render_field enquiry.hieuxe class="form-control" placeholder="Hiệu xe" %}

    <label for="vehicle_brand">Điện thoại</label>
    {% render_field enquiry.dienthoai class="form-control" placeholder="Điện thoại" %}

    <label for="vehicle_model">Địa chỉ</label>
    {% render_field enquiry.diachi class="form-control" placeholder="Địa chỉ" %}

    {% comment %} <label for="problem_description">Problem Description</label> {% endcomment %}
    {% comment %} {% render_field enquiry.problem_description class="form-control" placeholder="Problem Description" %} {% endcomment %}


    <input type="submit" value="Submit">
  </form>
</div>



<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
{% endblock content %}

templates/gara/bao_cao_doanh_thu.html
{% extends 'gara/customerbase.html' %}
{% block content %}




<head>

    <style>
         .form_container{
            max-width: 720px;
            height: 100px;
            padding: 15px;
            margin: auto;   
            display: flex;
            justify-content: center;
            /* background-color: aqua; */
        }

        .form_search{
            width: 500px;
            background-color: rgb(104, 195, 234);
            border-radius: 10px;
            display: inline-flex;
            justify-content: center;
            align-items: center;
        }
        .form-control{
            /* width: 90px; */
            min-height: 30px;
            border-radius: 5px;
            border: none;
        }
        .mr-sm-1{
            margin-right: 10px;
        }
        .submit{
            background-color: rgb(30, 173, 73);
            color: aliceblue;
            border: none;
            width: 90px;
            min-height: 30px;
            border-radius: 5px;
            /* margin: 15px ; */
        }
        .submit:hover{
            background-color: #53e994;
            cursor: pointer;
        }

        .card-content{
            /* background-color: antiquewhite; */
            display: flex;
            justify-content: center;
        }
        
        /* ========= table=========== */
        table {
            border-collapse: collapse;
            width: 75%;
        }
        th {
            background-color: #04AA6D;
            color: white;
        }

        th, td {
            padding: 8px;
            text-align: left;
            border-bottom: 1px solid #ddd;
        }
        tr:nth-child(even) {background-color: #a5e2fd;}

    </style>
</head>
<body>
    <br><br><br><br><br>
<h1 style="text-align:center;">Báo cáo doanh số</h1>


<div class="form_container" >
    <form action="../{{customer.username}}/post_bsds" class="form_search">
        {% csrf_token %}
        <input class="form-control mr-sm-1" name="m" type="search" placeholder="Month Search" aria-label="Search">
        <input class="form-control mr-sm-1" name="y" type="search" placeholder="Year Search" aria-label="Search">
        <button type="submit" class="submit mr-sm-3">Search</button>
    </form>
</div>


<div class="card-content">
    <table>
        <thead>
            <tr>
                <th>Tháng</th>
                <th>Năm</th>
                <th>Doanh số</th>
            </tr>
        </thead>
        <tbody>
        {% for i in bcds %}
        <tr>
            <td> {{ i.month }}</td>
            <td> {{ i.year }}</td>
            <td> {{ i.tongdoanhso }}</td>
        </tr>
        {% endfor %}
        </tbody>
    </table>
</div>


<h1 style="text-align:center;">Chi tiết báo cáo doanh số</h1>
<div class="card-content">
    <table>
        <thead>
            <tr>
                <th>STT</th>
                <th>Tên hiệu xe</th>
                <th>Số lượt sửa</th>
                <th>Thành tiền</th>
                <th>tỉ lệ</th>
            </tr>
        </thead>
        <tbody>
            {% for i in ct_bcds %}
            <tr>
                <td> {{ i.STT}}</td>
                <td> {{ i.tenhieuxe }}</td>
                <td> {{ i.luotsua }}</td>
                <td> {{ i.thanhtien }}</td>
                <td> {{ i.ti_le }}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
</body>
{% endblock content %}

templates/gara/baocaoton.html
{% extends 'gara/customerbase.html' %}
{% block content %}
	<!-- main content -->
	{% comment %} <div class="wrapper"> {% endcomment %}


<!-- ****** table  start ********** -->
<div class="wrapper">
    
    <div style="margin-left:0px;" class="container">
        
        <div class="row">
            <div class="col-12 col-m-12 col-sm-12">
                <div class="card">
                    <div class="card-header">
						<h2 style="color:red; text-align:center" >Báo cáo tồn </h2>
                        <h3 style="color:red; text-align:center"> {{month}}</h3>
						
					</div>
					<div class="card-content">
                
                            <table id="example" class="table table-striped" >
                                <thead>
                                    <tr>
                                        {% comment %} <th>STT</th> {% endcomment %}
                                        <th>STT</th>
                                        <th>Vật tư phụ tùng</th>
                                        <th>Tồn đầu</th>
                                        <th>Phát sinh</th>
                                        <th>Tồn cuối</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for enq in enquiries %}
                                    <tr>
                                      <td>{{enq.MaVTPT_id}}</td>
                                      <td>{{enq.MaVTPT.tenvattuphutung}}</td>
                                      <td>{{enq.TonDau}}</td>
                                      <td>{{enq.PhatSinh}}</td>
                                      <td>{{enq.TonCuoi}}</td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            
                            </table>
                        </div>
                    </div>
                    </div>           
        </div>
    </div>
</div>

{% endblock content %}

templates/gara/home.html
{% extends 'gara/customerbase.html' %}
{% block content %}
<div class="wrapper">
    <h2>Welcome to our site</h2>
    <p>Already have an account. <a href="/login">Login now !</a> </p>
    <p>If not, let's <a href="/signUp">create one</a></p>
    </div>
{% endblock %}

templates/gara/view_request.html
{% extends 'gara/customerbase.html' %}
{% block content %}

<style type="text/css">
    a:link {
      text-decoration: none;
    }

    h6 {
      color: white;
      font-size: 0.90em;
    }

    .order-card {
      color: #fff;
    }

    .bg-c-blue {
      background: linear-gradient(45deg, #4099ff, #73b4ff);
    }

    .bg-c-green {
      background: linear-gradient(45deg, #2ed8b6, #59e0c5);
    }

    .bg-c-yellow {
      background: linear-gradient(45deg, #FFB64D, #ffcb80);
    }

    .bg-c-pink {
      background: linear-gradient(45deg, #FF5370, #ff869a);
    }


    .card {
      border-radius: 5px;
      -webkit-box-shadow: 0 1px 2.94px 0.06px rgba(4, 26, 55, 0.16);
      box-shadow: 0 1px 2.94px 0.06px rgba(4, 26, 55, 0.16);
      border: none;
      margin-bottom: 30px;
      -webkit-transition: all 0.3s ease-in-out;
      transition: all 0.3s ease-in-out;
    }

    .card .card-block {
      padding: 25px;
    }

    .order-card i {
      font-size: 26px;
    }

    .f-left {
      float: left;
    }

    .f-right {
      float: right;
    }
    h6{
      size:20;
    }
  </style>
	<!-- main content -->
 
	<div class="wrapper">

		{% comment %} <a href="/"><button class="bn632-hover bn26">Lập phiếu tiếp nhận xe</button></a> {% endcomment %}
		<div style="margin-left:0px;" class="container">
			<div class="row">
			  <div class="col-md-4 col-xl-3">
				<div class="card bg-c-green order-card">
					<div class="card-block">
					  <a href="../{{customer.username}}/add_request">
						<h6 class="m-b-20">Tạo yêu cầu tiếp nhận xe</h6>
					  </a>
					  <h2 class="text-right"><i class="fas fa-plus-circle f-left"></i></h2>
					  <br>
					</div>
				  </div>
			  </div>
			</div>
		</div>
				<!-- ****** table  start ********** -->
        {% for message in messages %}
        <p {% if message.tags %} class="{{ message.tags }}" id="message_container" {% endif %}>{{ message }}</p>
        {% endfor %}
		<div class="row">
			<div class="col-12 col-m-12 col-sm-12">
			
						
				<div class="card">
					<div class="card-header">
										  
						<h2 style="color:red; text-align:center" >Danh sách xe đã tiếp nhận trong ngày</h2>
						

					</div>
					<div class="card-content">
						<table>
							<thead>
								<tr>
								<th>Biển số</th>
								<th>Hiệu xe</th>
								<th>Tên chủ xe</th>
								<th>Điện thoại</th>
								<th>Địa chỉ</th>
								<th>Ngày tiếp nhận</th>
                <th>Sửa</th>
								</tr>
							</thead>
							<tbody>
                {% for enq in enquiries %}
                <tr>
                  <td>{{enq.bienso}}</td>
                  <td>{{enq.hieuxe}}</td>
                  <td>{{enq.tenchuxe}}</td>
                  <td>{{enq.dienthoai}}</td>
                  <td>{{enq.diachi}}</td>
                  <td>{{enq.date}}</td>
                  <td><a  style="color:red; text-decoration:none;font-size:25px;" href="{% url 'gara:update_request' username=customer.username pk=enq.maphieutiepnhan %}">&#9998;</a></td>
                </tr>
                {% endfor %}

							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
		
   
<!-- ****** table start ********** -->
<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
	</div>
	<!-- end main content -->
{% endblock content %}